[program:app]
command=/bin/bash -c "cd /home/work && python3 -m uvicorn server.app:server --host 0.0.0.0 --port 8080"
directory=/home/work
autostart=true
autorestart=true
loglevel=info
minfds=1024
minprocs=200
user=work
nodaemon=false
stderr_logfile=/home/work/logs/app.err.log
stdout_logfile=/home/work/logs/app.out.log