/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetAllApiRawMsgGetParams = {
page?: number | null;
page_size?: number | null;
message_id?: string | null;
keyword?: string | null;
priority?: string | null;
start_date?: string | null;
end_date?: string | null;
has_bot_reply?: string | null;
bot_processed?: string | null;
duty_user?: string | null;
problem_category?: string | null;
has_qa_tracking?: string | null;
with_reply?: boolean | null;
};
