/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListMessagesApiMessageGetParams = {
/**
 * 为 true 时同时返回主消息下 raw_data.parent_id 指向主消息 id 的回复
 */
withReply?: boolean;
/**
 * 页码，从 1 开始
 * @minimum 1
 */
page?: number;
/**
 * 每页条数。不传则不分页，返回全部（导出场景用）
 */
pageSize?: number | null;
/**
 * 按用户原文模糊搜索
 */
keyword?: string | null;
/**
 * 按机器人问题分类过滤
 */
problemCategory?: string | null;
/**
 * 反馈起始日期 YYYY-MM-DD（含）
 */
startDate?: string | null;
/**
 * 反馈结束日期 YYYY-MM-DD（含）
 */
endDate?: string | null;
/**
 * 机器人是否处理过：yes / no
 */
hasBotProcessed?: string | null;
/**
 * 按值班人模糊匹配（关联 duty_schedule 表）
 */
dutyUser?: string | null;
/**
 * 问题原因是否已跟进：yes / no
 */
hasQaTracking?: string | null;
};
