/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MessageParsedData } from './messageParsedData';
import type { MessageRawData } from './messageRawData';

export interface Message {
  id: string;
  type?: string | null;
  parsed_data?: MessageParsedData;
  raw_data?: MessageRawData;
}
