/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from './message';
import type { MessageWithRepliesParsedData } from './messageWithRepliesParsedData';
import type { MessageWithRepliesRawData } from './messageWithRepliesRawData';

/**
 * 主消息 + 嵌套回复。仅用于响应序列化（orval 会据此生成前端类型）。
 */
export interface MessageWithReplies {
  id: string;
  type?: string | null;
  parsed_data?: MessageWithRepliesParsedData;
  raw_data?: MessageWithRepliesRawData;
  /** 嵌套回复列表 */
  replies?: Message[];
}
