/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from './message';

export interface PageMessage {
  /** 当前页数据 */
  items?: Message[];
  /** 总条数 */
  total?: number;
  /** 当前页码，从 1 开始 */
  page?: number;
  /** 每页条数 */
  pageSize?: number;
}
