/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StatsApiMessageStatsGetParams = {
/**
 * 起始日期 YYYY-MM-DD（默认近 7 天）
 */
start_date?: string | null;
/**
 * 结束日期 YYYY-MM-DD（默认今天）
 */
end_date?: string | null;
};
