/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StatsApiRawMsgStatsGetParams = {
start_date?: string | null;
end_date?: string | null;
};
