/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 同步请求体
 */
export interface SyncRequest {
  /** continue=从上次继续, range=指定时间段 */
  mode?: string;
  /** 起始日期 YYYY-MM-DD */
  start?: string | null;
  /** 结束日期 YYYY-MM-DD */
  end?: string | null;
}
