/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 上传工单到飞书多维表格的请求体
 */
export interface UploadRequest {
  /** 起始日期 YYYY-MM-DD */
  start_date?: string | null;
  /** 结束日期 YYYY-MM-DD */
  end_date?: string | null;
  /** 多维表格 App Token */
  app_token?: string;
  /** 多维表格 Table ID */
  table_id?: string;
}
