/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 上传结果
 */
export interface UploadResponse {
  total: number;
  uploaded: number;
  failed: number;
  errors: string[];
}
