/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  UploadRequest,
  UploadResponse
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 从 PG 读取值班表数据
 * @summary Duty Records
 */
export const dutyRecordsApiBitableDutyRecordsGet = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/bitable/duty-records`, method: 'GET'
    },
      options);
    }
  /**
 * 从 PG 读取 QA 跟进（问题原因）表数据
 * @summary Qa Tracking Records
 */
export const qaTrackingRecordsApiBitableQaTrackingRecordsGet = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/bitable/qa-tracking-records`, method: 'GET'
    },
      options);
    }
  /**
 * 手动同步值班表（飞书多维表格 → PG）
 * @summary Sync Duty
 */
export const syncDutyApiBitableSyncDutyPost = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/bitable/sync-duty`, method: 'POST'
    },
      options);
    }
  /**
 * 手动同步 QA 跟进（问题原因）表（飞书多维表格 → PG）
 * @summary Sync Qa Tracking
 */
export const syncQaTrackingApiBitableSyncQaTrackingPost = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/bitable/sync-qa-tracking`, method: 'POST'
    },
      options);
    }
  /**
 * 将指定日期范围内的工单批量上传到飞书多维表格
 * @summary Upload
 */
export const uploadApiBitableUploadPost = (
    uploadRequest: UploadRequest,
 options?: SecondParameter<typeof customAxiosInstance<UploadResponse>>,) => {
      return customAxiosInstance<UploadResponse>(
      {url: `/api/bitable/upload`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uploadRequest
    },
      options);
    }
  export type DutyRecordsApiBitableDutyRecordsGetResult = NonNullable<Awaited<ReturnType<typeof dutyRecordsApiBitableDutyRecordsGet>>>
export type QaTrackingRecordsApiBitableQaTrackingRecordsGetResult = NonNullable<Awaited<ReturnType<typeof qaTrackingRecordsApiBitableQaTrackingRecordsGet>>>
export type SyncDutyApiBitableSyncDutyPostResult = NonNullable<Awaited<ReturnType<typeof syncDutyApiBitableSyncDutyPost>>>
export type SyncQaTrackingApiBitableSyncQaTrackingPostResult = NonNullable<Awaited<ReturnType<typeof syncQaTrackingApiBitableSyncQaTrackingPost>>>
export type UploadApiBitableUploadPostResult = NonNullable<Awaited<ReturnType<typeof uploadApiBitableUploadPost>>>
