/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetMsgsApiLarkMsgGetParams
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Get Msgs
 */
export const getMsgsApiLarkMsgGet = (
    params?: GetMsgsApiLarkMsgGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/lark-msg/`, method: 'GET',
        params
    },
      options);
    }
  export type GetMsgsApiLarkMsgGetResult = NonNullable<Awaited<ReturnType<typeof getMsgsApiLarkMsgGet>>>
