/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllApiRawMsgGetParams,
  StatsApiRawMsgStatsGetParams,
  SyncRequest
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Stats
 */
export const statsApiRawMsgStatsGet = (
    params?: StatsApiRawMsgStatsGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/stats`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Get All
 */
export const getAllApiRawMsgGet = (
    params?: GetAllApiRawMsgGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Get Replies
 */
export const getRepliesApiRawMsgMessageIdRepliesGet = (
    messageId: string,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/${messageId}/replies`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Sync
 */
export const syncApiRawMsgSyncPost = (
    syncRequest: SyncRequest,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncRequest
    },
      options);
    }
  /**
 * @summary Clear All
 */
export const clearAllApiRawMsgAllDelete = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/all`, method: 'DELETE'
    },
      options);
    }
  export type StatsApiRawMsgStatsGetResult = NonNullable<Awaited<ReturnType<typeof statsApiRawMsgStatsGet>>>
export type GetAllApiRawMsgGetResult = NonNullable<Awaited<ReturnType<typeof getAllApiRawMsgGet>>>
export type GetRepliesApiRawMsgMessageIdRepliesGetResult = NonNullable<Awaited<ReturnType<typeof getRepliesApiRawMsgMessageIdRepliesGet>>>
export type SyncApiRawMsgSyncPostResult = NonNullable<Awaited<ReturnType<typeof syncApiRawMsgSyncPost>>>
export type ClearAllApiRawMsgAllDeleteResult = NonNullable<Awaited<ReturnType<typeof clearAllApiRawMsgAllDelete>>>
