/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Home
 */
export const homeApiHomeGet = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/home`, method: 'GET'
    },
      options);
    }
  export type HomeApiHomeGetResult = NonNullable<Awaited<ReturnType<typeof homeApiHomeGet>>>
