/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  Message,
  QueryApiMessageGetParams,
  SyncRequest
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Query
 */
export const queryApiMessageGet = (
    params?: QueryApiMessageGetParams,
 options?: SecondParameter<typeof customAxiosInstance<Message | Message[]>>,) => {
      return customAxiosInstance<Message | Message[]>(
      {url: `/api/message`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Sync
 */
export const syncApiMessageSyncPost = (
    syncRequest: SyncRequest,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/message/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncRequest
    },
      options);
    }
  export type QueryApiMessageGetResult = NonNullable<Awaited<ReturnType<typeof queryApiMessageGet>>>
export type SyncApiMessageSyncPostResult = NonNullable<Awaited<ReturnType<typeof syncApiMessageSyncPost>>>
