/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetMessageApiMessageMessageIdGetParams,
  ListMessagesApiMessageGetParams,
  Message,
  MessageWithReplies,
  PageMessage,
  PageMessageWithReplies,
  StatsApiMessageStatsGetParams,
  SyncRequest
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * 主消息列表查询，支持多条件筛选 + 分页 / 不分页（导出）。
 * @summary List Messages
 */
export const listMessagesApiMessageGet = (
    params?: ListMessagesApiMessageGetParams,
 options?: SecondParameter<typeof customAxiosInstance<PageMessageWithReplies | PageMessage>>,) => {
      return customAxiosInstance<PageMessageWithReplies | PageMessage>(
      {url: `/api/message`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Sync
 */
export const syncApiMessageSyncPost = (
    syncRequest: SyncRequest,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/message/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncRequest
    },
      options);
    }
  /**
 * 数据分析：当前周期 vs 前一周期的工单/机器人统计 + 问题分类分布
 * @summary Stats
 */
export const statsApiMessageStatsGet = (
    params?: StatsApiMessageStatsGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/message/stats`, method: 'GET',
        params
    },
      options);
    }
  /**
 * 按 id 查询单条工单，找不到返回 404。
 * @summary Get Message
 */
export const getMessageApiMessageMessageIdGet = (
    messageId: string,
    params?: GetMessageApiMessageMessageIdGetParams,
 options?: SecondParameter<typeof customAxiosInstance<MessageWithReplies | Message | null>>,) => {
      return customAxiosInstance<MessageWithReplies | Message | null>(
      {url: `/api/message/${messageId}`, method: 'GET',
        params
    },
      options);
    }
  export type ListMessagesApiMessageGetResult = NonNullable<Awaited<ReturnType<typeof listMessagesApiMessageGet>>>
export type SyncApiMessageSyncPostResult = NonNullable<Awaited<ReturnType<typeof syncApiMessageSyncPost>>>
export type StatsApiMessageStatsGetResult = NonNullable<Awaited<ReturnType<typeof statsApiMessageStatsGet>>>
export type GetMessageApiMessageMessageIdGetResult = NonNullable<Awaited<ReturnType<typeof getMessageApiMessageMessageIdGet>>>
