/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  Message,
  MessageWithReplies,
  PageMessage,
  PageMessageWithReplies,
  QueryApiMessageGetParams,
  StatsApiMessageStatsGetParams,
  SyncRequest
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Query
 */
export const queryApiMessageGet = (
    params?: QueryApiMessageGetParams,
 options?: SecondParameter<typeof customAxiosInstance<MessageWithReplies | Message | PageMessageWithReplies | PageMessage | null>>,) => {
      return customAxiosInstance<MessageWithReplies | Message | PageMessageWithReplies | PageMessage | null>(
      {url: `/api/message`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Sync
 */
export const syncApiMessageSyncPost = (
    syncRequest: SyncRequest,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/message/sync`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncRequest
    },
      options);
    }
  /**
 * 数据分析：当前周期 vs 前一周期的工单/机器人统计 + 问题分类分布
 * @summary Stats
 */
export const statsApiMessageStatsGet = (
    params?: StatsApiMessageStatsGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/message/stats`, method: 'GET',
        params
    },
      options);
    }
  export type QueryApiMessageGetResult = NonNullable<Awaited<ReturnType<typeof queryApiMessageGet>>>
export type SyncApiMessageSyncPostResult = NonNullable<Awaited<ReturnType<typeof syncApiMessageSyncPost>>>
export type StatsApiMessageStatsGetResult = NonNullable<Awaited<ReturnType<typeof statsApiMessageStatsGet>>>
